export SHARED=/home/eshernan/projects/WRF/V4/
export LIBS=$SHARED/libs
export INSTALLERS=$SHARED/installer
export INSTALLER_PATH=$INSTALLERS
export GEO_STATIC_DATA=$SHARED/GEO_STATIC_DATA
export DOMAIN_NAME=MyDOMAIN
export GFS_DATA=$DOMAIN_NAME/GFS_DATA
export GFS_PLEVEL=p25